;(load "~/dunderscore/workspaces/git-repos/cl-gpio/main.lisp")
(in-package :cl-gpio) 

(let ((chip (gpiod-chip-open "/dev/gpiochip0"))
      (settings (gpiod-line-settings-new))
      (line-cfg (gpiod-line-config-new))
      (offset (cffi:foreign-alloc :uint))
      (request ()))
  (gpiod-line-settings-set-direction settings gpiod-line-direction-output)
  (gpiod-line-settings-set-output-value settings gpiod-line-value-active)
  (setf (cffi:mem-ref offset :uint) 24)
  (gpiod-line-config-add-line-settings line-cfg offset 1 settings)
  (setf request (gpiod-chip-request-lines chip (cffi:null-pointer) line-cfg))
  (gpiod-line-request-set-value request 24 gpiod-line-value-active)
  (sleep 3)
  (gpiod-line-request-set-value request 24 gpiod-line-value-inactive)
  (gpiod-chip-close chip)
  (cffi:foreign-free offset)
  (gpiod-line-settings-free settings)
  (gpiod-line-config-free line-cfg))

